Repository kuoss/lethe, pull requests merged in 2023-03, with the labels that each got.

#32 licenses ok
  Makefile
  docs/licenses.csv
Labels: size/M

#31 PR workflow 속도 개선
  .github/workflows/pr-workflow.yml
Labels: size/XS

#35 remove deprecated package usage
  testutil/testenv.go
Labels: size/XS

#36 workflow go-test
  testutil/testenv.go
Labels: size/XS, testing

#39 mock lethe-writer
  Makefile
  scripts/mock/delete.sh
  scripts/mock/fluent-bit.conf
  scripts/mock/logs.sh
  scripts/mock/mock.lua
  scripts/mock/restart.sh
  scripts/mock/status.sh
Labels: testing, size/L

#41 add Coveralls
  .github/workflows/pr-workflow.yml
Labels: size/XS

#42 add simple tests
  .github/workflows/workflow.yml
  .gitignore
  Makefile
  cli/logs_test.go
  cli/main_test.go
  cli/task_test.go
  codecov.yml
  config/config_test.go
  docs/go-licenses.csv
  go.mod
  go.sum
  letheql/query_test.go
  logs/logs_test.go
  scripts/test-cover.sh
  util/byte_test.go
  util/exec_test.go
  util/string_test.go
  util/time_test.go
Labels: size/L

#44 Refactoring minor
  logs/list.go
  testutil/testenv_disk_linux.go
  util/exec.go
  util/exec_test.go
  util/time.go
  util/time_test.go
Labels: size/M

#45 fix reconstruct package structure
  letheql/engine.go
  letheql/parser/parser.go
  letheql/parser/parser_test.go
  logs/init_test.go
Labels: size/L

#46 remove size-label
  .github/workflows/ci.yml
Labels: size/S

#47 change branch stragtegy ( develop -> main )
  .air.toml
  .github/workflows/ci.yml
  Makefile
  etc/lethe.yaml
  logs/list.go
  main.go
  testutil/testenv_disk_linux.go
  util/exec.go
  util/exec_test.go
  util/time.go
  util/time_test.go
Labels: size/L
