Repository kuoss/lethe, pull requests merged in 2023-02, with the labels that each got.

#12 PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#14 workflows size-label
  .github/workflows/size-label.yml
Labels: documentation

#21 Development branch
  .gitignore
  cli/cmd/list/list_dirs.go
  cli/cmd/list/list_files.go
  cli/cmd/list/list_targets.go
  cli/cmd/task/task_deleteByAge.go
  cli/cmd/task/task_deleteBySize.go
  config/config.go
  config/config_test.go
  etc/lethe.yaml
  file/delete_test.go
  file/list.go
  file/list_test.go
  file/logs.go
  file/logs_test.go
  file/types.go
  go.mod
  handlers/metadata.go
  handlers/query.go
  letheql/init_test.go
  letheql/parser_test.go
  letheql/query.go
  letheql/query_test.go
  logs/cleansing.go
  logs/delete.go
  logs/delete_test.go
  logs/filter.go
  logs/filter_test.go
  logs/init_test.go
  logs/list.go
  logs/list_test.go
  logs/logs.go
  logs/logs_test.go
  logs/rotator.go
  logs/rotator_test.go
  logs/types.go
  main.go
  routes.go
  routes_test.go
  routine/routine.go
  routine/routine_test.go
  storage/driver/factory/factory.go
  storage/driver/filesystem/driver.go
  storage/driver/filesystem/driver_test.go
  storage/driver/filesystem/factory.go
  storage/driver/filesystem/paths_test.go
  storage/driver/storagedriver.go
  storage/error.go
  storage/paths.go
  testutil/testutil.go
Labels: enhancement

#22 Dev
  .gitignore
  cli/cmd/list/list_dirs.go
  cli/cmd/list/list_files.go
  cli/cmd/list/list_targets.go
  cli/cmd/task/task_deleteByAge.go
  cli/cmd/task/task_deleteBySize.go
  config/config.go
  config/config_test.go
  etc/lethe.yaml
  file/delete_test.go
  file/list.go
  file/list_test.go
  file/logs.go
  file/logs_test.go
  file/types.go
  go.mod
  handlers/metadata.go
  handlers/query.go
  letheql/init_test.go
  letheql/parser_test.go
  letheql/query.go
  letheql/query_test.go
  logs/cleansing.go
  logs/delete.go
  logs/delete_test.go
  logs/filter.go
  logs/filter_test.go
  logs/init_test.go
  logs/list.go
  logs/list_test.go
  logs/logs.go
  logs/logs_test.go
  logs/rotator.go
  logs/rotator_test.go
  logs/types.go
  main.go
  routes.go
  routes_test.go
  routine/routine.go
  routine/routine_test.go
  storage/driver/factory/factory.go
  storage/driver/filesystem/driver.go
  storage/driver/filesystem/driver_test.go
  storage/driver/filesystem/factory.go
  storage/driver/filesystem/paths_test.go
  storage/driver/storagedriver.go
  storage/error.go
  storage/paths.go
  testutil/testutil.go
Labels: size/XXL

#18 readme에 뱃지 추가
  README.md
Labels: documentation, size/XS

#24 new-test-environment
  Makefile
  cli/cmd/list/list_dirs.go
  cli/cmd/list/list_files.go
  cli/cmd/list/list_targets.go
  cli/cmd/logs.go
  cli/cmd/task/task_deleteByAge.go
  cli/cmd/task/task_deleteBySize.go
  cli/init_test.go
  cli/list_test.go
  cli/logs_test.go
  cli/task_test.go
  clock/clock.go
  clock/clock_test.go
  config/config.go
  go.mod
  go.sum
  handlers/metadata.go
  handlers/query.go
  letheql/init_test.go
  letheql/parser_test.go
  letheql/query.go
  letheql/query_test.go
  logs/delete.go
  logs/delete_test.go
  logs/filter.go
  logs/filter_test.go
  logs/init_test.go
  logs/list.go
  logs/list_test.go
  logs/logs.go
  logs/logs_test.go
  logs/rotator.go
  logs/rotator_test.go
  main.go
  routes.go
  routes_test.go
  storage/driver/factory/factory.go
  storage/driver/filesystem/driver.go
  storage/driver/filesystem/driver_test.go
  storage/driver/filesystem/init_test.go
  storage/paths.go
  testutil/log/node/node01/2009-11-10_21.log
  testutil/log/node/node01/2009-11-10_22.log
  testutil/log/node/node02/2009-11-01_00.log
  testutil/log/node/node02/2009-11-10_21.log
  testutil/log/pod/namespace01/2000-01-01_00.log
  testutil/log/pod/namespace01/2009-11-10_21.log
  testutil/log/pod/namespace01/2009-11-10_22.log
  testutil/log/pod/namespace01/2029-11-10_23.log
  testutil/log/pod/namespace02/0000-00-00_00.log
  testutil/log/pod/namespace02/2009-11-10_22.log
  testutil/testenv.go
  testutil/testenv_test.go
  testutil/testutil.go
  testutil/testutil_test.go
  util/byte.go
Labels: size/XXL, testing
