Repository kuoss/lethe, pull requests merged in 2023-04, with the labels that each got.

#54 Develop reconstruction jsonoutput
  .github/workflows/workflow.yml
  cli/logs_test.go
  handlers/query.go
  letheql/promql_parse_test.go
  letheql/query.go
  letheql/query_test.go
  letheql/types.go
  logs/logStore/logStore.go
  logs/logStore/types.go
  routes_test.go
Labels: enhancement, size/L

#57 improve-workflow
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  routes_test.go
  scripts/test-cover.sh
  storage/driver/filesystem/driver.go
Labels: size/L, technical debt

#60 goimports
  .github/workflows/pull-request.yml
  .gitignore
  Dockerfile
  Dockerfile.dev
  Makefile
  cli/logs_test.go
  config/config_test.go
  hack/checks.sh
  hack/go-licenses.sh
  hack/list_dirs.sh
  hack/list_files.sh
  hack/mock/delete.sh
  hack/mock/fluent-bit.conf
  hack/mock/logs.sh
  hack/mock/mock.lua
  hack/mock/restart.sh
  hack/mock/status.sh
  hack/pod_log.sh
  hack/test-cover.sh
  hack/test-failfast.bat
  hack/test-failfast.sh
  logs/list.go
  logs/logs_test.go
  main.go
  scripts/go_test_all_packages_failfast.sh
  scripts/test-cover.sh
  storage/driver/filesystem/paths_test.go
  util/byte_test.go
  util/string_test.go
  util/time_test.go
Labels: size/L, refactoring, technical debt

#63 logger logrus singleton
  .gitignore
  Makefile
  docs/go-licenses.csv
  go.mod
  go.sum
  logger/logger.go
  logger/logger_test.go
  main.go
Labels: size/L

#68 go-test-coverage
  .github/workflows/pull-request.yml
Labels: size/S

#71 bugfix error handling + show settings on start
  Makefile
  cli/cmd/list/list_files.go
  cli/cmd/task/task_deleteByAge.go
  cli/cmd/task/task_deleteBySize.go
  cli/main.go
  config/config.go
  config/config_test.go
  docs/go-licenses.csv
  go.mod
  go.sum
  hack/test-failfast.sh
  logs/rotator/delete.go
  logs/rotator/delete_test.go
  logs/rotator/list.go
  logs/rotator/list_test.go
  logs/rotator/rotator.go
  main.go
  testutil/testenv.go
Labels: bug, size/L, refactoring

#73 config listen_address, log_data_path
  cli/task_test.go
  config/config.go
  config/config_inner_test.go
  config/config_outer_test.go
  config/config_test.go
  etc/lethe.yaml
  logs/logStore/logStore.go
  logs/rotator/cleansing.go
  logs/rotator/delete.go
  logs/rotator/delete_test.go
  logs/rotator/rotator.go
  logs/rotator/rotator_test.go
  logs/rotator/used_size.go
  main.go
  testutil/testenv.go
  testutil/testenv_test.go
Labels: enhancement, size/L, refactoring

#74 parser support piped multiple filter operators
  .gitignore
  docs/go-licenses.csv
  go.mod
  letheql/parser/Makefile
  letheql/parser/ast.go
  letheql/parser/functions.go
  letheql/parser/generated_parser.y
  letheql/parser/generated_parser.y.go
  letheql/parser/lex.go
  letheql/parser/lex_test.go
  letheql/parser/parse.go
  letheql/parser/parse_test.go
  letheql/parser/parser_inner_test.go
  letheql/parser/parser_outer_test.go
  letheql/parser/prettier.go
  letheql/parser/prettier_rules.md
  letheql/parser/prettier_test.go
  letheql/parser/printer.go
  letheql/parser/printer_test.go
  letheql/parser/value.go
  letheql/prom_parse_tset.go
  testutil/testcase.go
  testutil/testcase_inner_test.go
  testutil/testcase_outer_test.go
Labels: enhancement, size/XXL, refactoring
