Repository kuoss/lethe, pull requests merged in 2023-07, with the labels that each got.

#90 add fuzz test case within MatchFunc on Label.
  storage/logservice/match/label_test.go
Labels: testing, size/L

#92 fix DeleteBySize
  storage/fileservice/delete.go
Labels: bug, size/S

#95 clean bugfix
  etc/lethe.example.yaml
  storage/driver/driver.go
  storage/driver/error.go
  storage/driver/error_test.go
  storage/driver/filesystem/driver.go
  storage/driver/filesystem/driver_test.go
  storage/fileservice/clean.go
  storage/fileservice/clean_test.go
  storage/fileservice/list_test.go
Labels: bug, size/L
